//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Event_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingInfo_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookingInfo_tbl()
        {
            this.Booking_SeatInfo_tbl = new HashSet<Booking_SeatInfo_tbl>();
        }
    
        public int Booking_id { get; set; }
        public Nullable<int> fk_student_id { get; set; }
        public Nullable<int> fk_eventid { get; set; }
        public System.DateTime booking_date { get; set; }
        public string booking_time { get; set; }
        public int TotalbookSeat { get; set; }
        public decimal TotalPrice { get; set; }
        public System.DateTime Created_Date { get; set; }
        public Nullable<int> Created_by { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking_SeatInfo_tbl> Booking_SeatInfo_tbl { get; set; }
        public virtual Event_Tbl Event_Tbl { get; set; }
        public virtual Student_tbl Student_tbl { get; set; }
    }
}
