//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Event_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking_SeatInfo_tbl
    {
        public int bookingSeat_id { get; set; }
        public Nullable<int> fk_booking_id { get; set; }
        public System.DateTime Created_Date { get; set; }
        public Nullable<int> Created_by { get; set; }
    
        public virtual BookingInfo_tbl BookingInfo_tbl { get; set; }
    }
}
