//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Event_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event_Tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event_Tbl()
        {
            this.BookingInfo_tbl = new HashSet<BookingInfo_tbl>();
        }
    
        public int Event_Id { get; set; }
        public Nullable<int> FK_Event_Mst_Id { get; set; }
        public System.DateTime Event_FromDate { get; set; }
        public System.DateTime Event_ToDate { get; set; }
        public string Event_FromTime { get; set; }
        public string Event_ToTime { get; set; }
        public Nullable<int> fk_Event_Loc_id { get; set; }
        public decimal PriceperSeat { get; set; }
        public int maxSeatbookperuser { get; set; }
        public decimal Price { get; set; }
        public System.DateTime Created_Date { get; set; }
        public Nullable<int> Created_by { get; set; }
    
        public virtual EventMaster_Tbl EventMaster_Tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingInfo_tbl> BookingInfo_tbl { get; set; }
        public virtual EventLocationMaster_Tbl EventLocationMaster_Tbl { get; set; }
    }
}
