//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Event_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seat_tbl
    {
        public int Seat_id { get; set; }
        public string Seat_Name { get; set; }
        public string Seat_row { get; set; }
        public Nullable<int> FK_EventLoc_ID { get; set; }
        public Nullable<int> fk_Even_Mst_id { get; set; }
    
        public virtual EventLocationMaster_Tbl EventLocationMaster_Tbl { get; set; }
        public virtual EventMaster_Tbl EventMaster_Tbl { get; set; }
    }
}
