//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Event_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seat_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seat_tbl()
        {
            this.Booking_SeatInfo_tbl = new HashSet<Booking_SeatInfo_tbl>();
        }
    
        public int Seat_id { get; set; }
        public string Seat_Name { get; set; }
        public string Seat_row { get; set; }
        public Nullable<int> FK_EventLoc_ID { get; set; }
        public Nullable<int> fk_Even_Mst_id { get; set; }
        public Nullable<int> ISAVAIL { get; set; }
    
        public virtual EventMaster_Tbl EventMaster_Tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking_SeatInfo_tbl> Booking_SeatInfo_tbl { get; set; }
        public virtual EventLocationMaster_Tbl EventLocationMaster_Tbl { get; set; }
    }
}
