//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Event_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student_tbl()
        {
            this.BookingInfo_tbl = new HashSet<BookingInfo_tbl>();
        }
    
        public int Student_id { get; set; }
        public string Student_Code { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PinCode { get; set; }
        public string Mobile { get; set; }
        public string EmailId { get; set; }
        public Nullable<int> FKCollege_ID { get; set; }
        public Nullable<int> FkYearId { get; set; }
        public Nullable<int> FKSemID { get; set; }
        public System.DateTime Created_Date { get; set; }
        public Nullable<int> Created_by { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingInfo_tbl> BookingInfo_tbl { get; set; }
        public virtual Semester_Tbl Semester_Tbl { get; set; }
        public virtual Year_Tbl Year_Tbl { get; set; }
        public virtual College_Tbl College_Tbl { get; set; }
    }
}
